name: flutter_store
description: "A new Flutter project."

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/smart_light.png
  image_dark: assets/logos/smart_dark.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/smart_light.png
    image_dark: assets/logos/smart_dark.png

  web: false

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

#-----------------PACKAGES --------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.2
  intl: ^0.18.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.6
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0


  
  #ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #State Management
  get: ^4.0.5
  get_storage: ^2.1.1

  # Products
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  #firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.3.2+7
  firebase_messaging: ^15.2.9
  #delivery
  google_maps_flutter: ^2.0.10
  location: ^5.0.3
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  qr_flutter: ^4.1.0
  googleapis_auth: ^2.0.0



  uuid: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  
  flutter_lints: ^2.0.0



flutter:
  
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products_Images/
    - assets/images/user/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/icons/Poppins-Light.ttf
          weight: 300
        - asset: assets/icons/Poppins-Regular.ttf
          weight: 400
        - asset: assets/icons/Poppins-Italic.ttf
          style: italic
        - asset: assets/icons/Poppins-Medium.ttf
          weight: 500
        - asset: assets/icons/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/icons/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/icons/Poppins-Bold.ttf
          weight: 800