// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo7RoHNuo2USpMpRmrCDDsZAHHLgu3dsE',
    appId: '1:595350942491:web:abb4912a5aa2e2a45419be',
    messagingSenderId: '595350942491',
    projectId: 'ecommerceapp-a21e1',
    authDomain: 'ecommerceapp-a21e1.firebaseapp.com',
    storageBucket: 'ecommerceapp-a21e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qT8hypxY2_px6DvqkhE8bns_INJTQBE',
    appId: '1:595350942491:android:c9fe1b58cdfd419b5419be',
    messagingSenderId: '595350942491',
    projectId: 'ecommerceapp-a21e1',
    storageBucket: 'ecommerceapp-a21e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJamy10h_D6CeJo7BNpmgy8NGsgQy7qto',
    appId: '1:595350942491:ios:4cbc81fc0af2cf2b5419be',
    messagingSenderId: '595350942491',
    projectId: 'ecommerceapp-a21e1',
    storageBucket: 'ecommerceapp-a21e1.appspot.com',
    androidClientId: '595350942491-pj5pf2teftapoht7hqc2lpqd6cg8ulus.apps.googleusercontent.com',
    iosClientId: '595350942491-dsqela6lcbs5cersjcccoafttsmojamb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStore',
  );

}